Traceback (most recent call last):
  File "/home/panxopanza/miniconda3/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/panxopanza/miniconda3/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/panxopanza/miniconda3/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/panxopanza/miniconda3/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/panxopanza/miniconda3/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/panxopanza/miniconda3/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/panxopanza/miniconda3/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
from numpy import radians as rad # convertimos grados a radianes
import matplotlib.pyplot as plt
from empylib.waveoptics import interface

theta = np.linspace(0,90,1000) # √Ångulo de incidencia

# preparamos el ploteo
def plot_R_interface(n1,n2):
    
    # Reflectividad en una interface
    Rp = interface(rad(theta),n1,n2,pol='TM')[0] # TM
    Rs = interface(rad(theta),n1,n2,pol='TE')[0] # TE
    
    fig, ax = plt.subplots()
    fig.set_size_inches(5,3)
    plt.rcParams['font.size'] = '14'
    ax.plot(theta,Rp, label='$R_\mathrm{TM}$', color='red')
    ax.plot(theta,Rs, label='$R_\mathrm{TE}$',color='blue')
    ax.set_xlim([0,90])
    ax.set_ylim([0,1.0])
    ax.set_xlabel('√Ångulo de incidencia (¬∞)')
    ax.set_ylabel('Reflectividad')
    ax.legend(frameon=False)
    plt.show()
------------------

----- stderr -----
<>:18: SyntaxWarning: invalid escape sequence '\m'
<>:19: SyntaxWarning: invalid escape sequence '\m'
<>:18: SyntaxWarning: invalid escape sequence '\m'
<>:19: SyntaxWarning: invalid escape sequence '\m'
/tmp/ipykernel_162/1492845190.py:18: SyntaxWarning: invalid escape sequence '\m'
  ax.plot(theta,Rp, label='$R_\mathrm{TM}$', color='red')
/tmp/ipykernel_162/1492845190.py:19: SyntaxWarning: invalid escape sequence '\m'
  ax.plot(theta,Rs, label='$R_\mathrm{TE}$',color='blue')
/tmp/ipykernel_162/1492845190.py:18: SyntaxWarning: invalid escape sequence '\m'
  ax.plot(theta,Rp, label='$R_\mathrm{TM}$', color='red')
/tmp/ipykernel_162/1492845190.py:19: SyntaxWarning: invalid escape sequence '\m'
  ax.plot(theta,Rs, label='$R_\mathrm{TE}$',color='blue')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[4], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mimport[39;00m radians [38;5;28;01mas[39;00m rad [38;5;66;03m# convertimos grados a radianes[39;00m
[0;32m----> 3[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mempylib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mwaveoptics[39;00m [38;5;28;01mimport[39;00m interface
[1;32m      6[0m theta [38;5;241m=[39m np[38;5;241m.[39mlinspace([38;5;241m0[39m,[38;5;241m90[39m,[38;5;241m1000[39m) [38;5;66;03m# √Ångulo de incidencia[39;00m

[0;31mModuleNotFoundError[0m: No module named 'matplotlib'

